In [ ]:
import pandas as pd
import glob
from functools import reduce

In [22]:
dfvax = pd.read_csv('2022VAERSVAX.csv')
dfvax.head(1)

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,1996873,HPV9,MERCK & CO. INC.,R017624,UNK,NaN,NaN,HPV (GARDASIL 9)

In [24]:
dfsymptoms = pd.read_csv('2022VAERSSYMPTOMS.csv')
dfsymptoms.head(1)

,VAERS_ID,SYMPTOM1,SYMPTOMVERSION1,SYMPTOM2,SYMPTOMVERSION2,SYMPTOM3,SYMPTOMVERSION3,SYMPTOM4,SYMPTOMVERSION4,SYMPTOM5,SYMPTOMVERSION5
0,1996873,Expired product administered,24.1,No adverse event,24.1,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
dfdata = pd.read_csv('2022VAERSDATA.csv')
dfdata.head(1)

/var/folders/46/524r89fx7lg2l1kjzxdwg49h0000gn/T/ipykernel_34861/575485479.py:1: DtypeWarning: Columns (7,12,23) have mixed types. Specify dtype option on import or set low_memory=False.
  dfdata = pd.read_csv('2022VAERSDATA.csv')

,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,DIED,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,1996873,1/1/22,CA,NaN,NaN,NaN,U,NaN,This spontaneous report was received from a ph...,NaN,...,NaN,NaN,NaN,US0095075132112USA007320,2,12/31/21,NaN,NaN,NaN,NaN

In [26]:
merged = pd.concat([dfvax, dfdata], axis=1)
merged.head()

,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME,VAERS_ID,RECVDATE,...,CUR_ILL,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES
0,1996873,HPV9,MERCK & CO. INC.,R017624,UNK,NaN,NaN,HPV (GARDASIL 9),1996873.0,1/1/22,...,NaN,NaN,NaN,US0095075132112USA007320,2.0,12/31/21,NaN,NaN,NaN,NaN
1,1996874,COVID19,JANSSEN,NaN,1,OT,NaN,COVID19 (COVID19 (JANSSEN)),1996874.0,1/1/22,...,NaN,NaN,NaN,USJNJFOC20211263430,2.0,1/1/22,NaN,NaN,NaN,NaN
2,1996875,COVID19,JANSSEN,204A21A,1,NaN,NaN,COVID19 (COVID19 (JANSSEN)),1996875.0,1/1/22,...,NaN,NaN,NaN,USJNJFOC20211266010,2.0,1/1/22,NaN,NaN,NaN,NaN
3,1996876,COVID19,PFIZER\BIONTECH,Fd8448,2,NaN,LA,COVID19 (COVID19 (PFIZER-BIONTECH)),1996876.0,1/1/22,...,NaN,Comments: List of non-encoded Patient Relevant...,NaN,USPFIZER INC202101162241,2.0,12/31/21,NaN,NaN,NaN,NaN
4,1996877,COVID19,PFIZER\BIONTECH,EP6955,1,NaN,LA,COVID19 (COVID19 (PFIZER-BIONTECH)),1996877.0,1/1/22,...,NaN,NaN,NaN,USPFIZER INC202101281356,2.0,12/31/21,NaN,NaN,NaN,NaN